In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

Day 1

**Activation function**

In [ ]:
def sigmoid(x):
  return 1/(1+math.exp(-x))

In [ ]:
sigmoid(1)

0.7310585786300049

In [ ]:
sigmoid(1000)

1.0

Tanh

In [ ]:
def Tanh(x):
  return math.exp(x)-math.exp(-x)/(math.exp(x)+math.exp(-x))

In [ ]:
Tanh(-499)

-1.0

In [ ]:
Tanh(10)

22026.465794804655

In [ ]:
Tanh(0)

0.5

ReLU

In [ ]:
def Relu(x):
  return(max(0,x))

In [ ]:
Relu(-56)

0

In [ ]:
Relu(456)

456

In [ ]:
Relu(0)

0

Leaky Relu

In [ ]:
def LeakyRelu(x):
  return(max(0.01*x,x))

In [ ]:
LeakyRelu(-56)

-0.56

ELU

In [ ]:
import numpy as np

def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))


In [ ]:
elu(45)

array(45.)

SELU

In [ ]:
# SELU

import numpy as np

def selu(x, alpha=1.6733, scale=1.0507):
    return scale * np.where(x > 0, x, alpha * (np.exp(x) - 1))


In [ ]:
selu(0)

0.0

**Day1 (01/01/2023)**

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/insurance_data (1) (1).csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [ ]:
df.shape

(28, 3)

In [ ]:
#splitting the dataset into training and testing
from sklearn.model_selection  import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=20)

In [ ]:
len(X_train)

22

In [ ]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100



In [ ]:
X_train_scaled

age  affordibility
18  0.19              0
25  0.54              1
23  0.45              1
22  0.40              1
21  0.26              0
5   0.56              1
24  0.50              1
19  0.18              1
14  0.49              1
17  0.58              1
6   0.55              0
16  0.25              0
8   0.62              1
0   0.22              1
2   0.47              1
7   0.60              0
11  0.28              1
20  0.21              1
9   0.61              1
15  0.55              1
26  0.23              1
3   0.52              0

In [ ]:
model2=keras.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')])

model2.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])
model2.fit(X_train_scaled,y_train,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 672ms/step - loss: 0.6459 - accuracy: 0.5909
Epoch 2/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6456 - accuracy: 0.5909
Epoch 3/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6454 - accuracy: 0.5909
Epoch 4/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6451 - accuracy: 0.5909
Epoch 5/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6448 - accuracy: 0.5909
Epoch 6/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6446 - accuracy: 0.5909
Epoch 7/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6443 - accuracy: 0.5909
Epoch 8/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6441 - accuracy: 0.5909
Epoch 9/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6438 - accuracy: 0.5909
Epoch 10/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6435 - accuracy: 0.5909
Epoch 11

In [ ]:
model2.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 160ms/step - loss: 0.7027 - accuracy: 0.6667


[0.7027472853660583, 0.6666666865348816]

In [ ]:
model2.predict(X_test_scaled)

1/1 [==============================] - 0s 76ms/step


array([[0.46081197],
       [0.69935626],
       [0.44169077],
       [0.5753304 ],
       [0.69935626],
       [0.45123342]], dtype=float32)

In [ ]:
y_test

13    0
4     1
1     0
10    0
27    0
12    0
Name: bought_insurance, dtype: int64

In [ ]:
weight,bias=model2.get_weights()
weight,bias

(array([[1.9307189 ],
        [0.67308617]], dtype=float32),
 array([-0.71698266], dtype=float32))

In [ ]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))


In [ ]:
a=np.array([1,2,3,4])
sigmoid_numpy(a)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [ ]:
def log_loss(y_true,y_pred):
  e=1e-10
  y_pred_new=[max(i,e)for i in y_pred]
  y_pred_new=[min(i,1-e) for i in y_pred_new]
  y_pred_new=np.array(y_pred_new)

  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [ ]:
a=np.array([1,2,3,4])
sigmoid_numpy(a)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [ ]:
def gradient_descent(age,aff,y_t,epochs,loss_thr):
  w1=1
  w2=1
  b=0
  n=len(age)
  lear_rate=0.5

  for i in range(epochs):
    weighted_sum=w1*age+w2*aff+b
    y_p=sigmoid_numpy(weighted_sum)
    loss=log_loss(y_t,y_p)

    w1_d = (1/n)*np.dot((age),np.transpose(y_p-y_t))
    w2_d = (1/n)*np.dot((aff),(y_p-y_t))

    b_d = np.mean(y_p-y_t)

    w1=w1-lear_rate*w1_d
    w2 = w2 -lear_rate * w2_d
    b=b- b-lear_rate* b_d

    print ('Epoch:',{i}, 'w1:',{w1}, 'w2:',{w2}, 'b:',{b}, 'loss:',{loss})
    if loss<loss_thr:
            break

  return w1, w2, b



In [ ]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,100, 0.55)

Epoch: {0} w1: {0.9899044631276738} w2: {0.9569405919425348} b: {-0.07899372792977674} loss: {0.645879853336323}
Epoch: {1} w1: {0.9839956437241003} w2: {0.9213120476683795} b: {-0.0688390953074361} loss: {0.6306399722613678}
Epoch: {2} w1: {0.9787178553939094} w2: {0.8874026149929113} b: {-0.06737928527992336} loss: {0.6294794564509504}
Epoch: {3} w1: {0.974367907425216} w2: {0.8556628910507127} b: {-0.06518966676249639} loss: {0.6273958016852729}
Epoch: {4} w1: {0.9708591802332485} w2: {0.825922920160302} b: {-0.0632060896639361} loss: {0.6256912276053487}
Epoch: {5} w1: {0.9681442497574754} w2: {0.7980764627879908} b: {-0.06133280445345248} loss: {0.6242036606799187}
Epoch: {6} w1: {0.9661727240114698} w2: {0.7720126668456061} b: {-0.059576974303892104} loss: {0.6229161122023454}
Epoch: {7} w1: {0.9648959255052931} w2: {0.7476239745542741} b: {-0.057934416123035515} loss: {0.6218009644418351}
Epoch: {8} w1: {0.9642667072247068} w2: {0.7248060153983343} b: {-0.05640145004053357} loss

(1.4178561717022837, 0.2542112098200537, -0.041769609415973956)

In [ ]:
weight,bias

(array([[1.9307189 ],
        [0.67308617]], dtype=float32),
 array([-0.71698266], dtype=float32))

In [ ]:
import random

In [ ]:
def log_loss_sto(y_true,y_pred):
  e=1e-10
  y_pred_new=max(y_pred,e)
  y_pred_new=min(y_pred_new,1-e)
  y_pred_new=np.array(y_pred_new)

  return -(y_true*math.log(y_pred_new)+(1-y_true)*math.log(1-y_pred_new))

**SGD**

In [ ]:
class ANN:
  def __init__(self):
    self.w1=1
    self.w2=1
    self.b=0

  def fit(self,X,y,epochs):
      self.sto_gradient_descent(X["age"],X["affordibility"],y,epochs)

  def sto_gradient_descent(self,age,aff,y_t,Epochs):
          w1=1
          w2=1
          b=0
          n=len(age)
          learning_rate=0.5

          age_new=np.array(age)
          aff_new=np.array(aff)
          y_t=np.array(y_t)

          for i in range(Epochs):
            r=random.randint(0,len(age_new)-1)
            weighted_sum = w1 * age_new[r] + w2 * aff_new[r] + b
            y_p= sigmoid_numpy(weighted_sum)
            loss=log_loss_sto(y_t[r],y_p)

            w1_d=(age_new[r]*(y_p-y_t[r]))
            w2_d=(aff_new[r]*(y_p-y_t[r]))
            b_d=(y_p-y_t[r])

            w1=1-learning_rate*w1_d
            w2=2-learning_rate*w2_d
            b=b-learning_rate*b_d



            print("Epochs:",i,"w1:",w1,"w2:",w2,"b:",b,"loss:",loss)
          return w1,w2,b

  def predict(self, X):
        W_S = self.w1 * X["age_new"] + self.w2 * X["affordibility_new"] + self.b
        y_pred = self.sigmoid(W_S)
        return y_pred

  def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

In [ ]:
sto_model2=ANN()
sto_model2.fit(X_train_scaled,y_train,1000)

Epochs: 0 w1: 0.9191186103501068 w2: 1.6148505254766992 b: -0.38514947452330095 loss: 1.4709765939671287
Epochs: 1 w1: 1.0389682838137893 w2: 2.0779365676275785 b: -0.30721290689572234 loss: 0.16945248200342533
Epochs: 2 w1: 1.0239020252533215 w2: 2.044263009728373 b: -0.26294989716734923 loss: 0.09269223102702416
Epochs: 3 w1: 1.0221540756068002 w2: 2.047136331078298 b: -0.21581356608905095 loss: 0.09901696984190328
Epochs: 4 w1: 1.0216807367578054 w2: 2.0442464015465416 b: -0.17156716454250948 loss: 0.09265578922051752
Epochs: 5 w1: 0.9519644085332518 w2: 2.0 b: -0.424386066999079 loss: 0.7044868420106072
Epochs: 6 w1: 1.1390102834809248 w2: 2.0 b: -0.19270226119753764 loss: 0.6224419842640044
Epochs: 7 w1: 0.9316411809838185 w2: 2.0 b: -0.4556207958751584 loss: 0.7462042808131208
Epochs: 8 w1: 1.0256384983393556 w2: 2.064096245848389 b: -0.3915245500267693 loss: 0.1371866268001325
Epochs: 9 w1: 1.0252675198987764 w2: 2.050535039797553 b: -0.3409895102292166 loss: 0.1065502003800371


**MINI BATCH GRADIENT DESCENT**

In [ ]:
def log_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return -(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def log_loss_mini_batch(y_true, y_pred):
    return np.mean(log_loss(y_true, y_pred))

In [ ]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))


In [ ]:
class ANN:
  def __init__(self):
    self.w1=1
    self.w2=1
    self.b=0

  def fit(self,X,y,epochs,batch_size):
      self.mini_batch_gradient_descent(X["age"],X["affordibility"],y,epochs,batch_size)

  def mini_batch_gradient_descent(self, age, aff, y_t, epochs, batch_size):
    w1 = 1
    w2 = 1
    b = 0
    n = len(age)
    lear_rate = 0.5

    age = np.array(age)
    aff = np.array(aff)
    y_t = np.array(y_t)

    for i in range(epochs):
        indices = np.random.choice(n, size=batch_size, replace=False)
        batch_age = age[indices]
        batch_aff = aff[indices]
        batch_y_t = y_t[indices]

        weighted_sum = w1 * batch_age + w2 * batch_aff + b
        y_p = sigmoid_numpy(weighted_sum)
        loss = log_loss_mini_batch(batch_y_t, y_p)

        w1_d = np.mean(batch_age * (y_p - batch_y_t))
        w2_d = np.mean(batch_aff * (y_p - batch_y_t))
        b_d = np.mean(y_p - batch_y_t)

        w1 = w1 - lear_rate * w1_d
        w2 = w2 - lear_rate * w2_d
        b = b - lear_rate * b_d

        print('Epoch:', i, 'w1:', w1, 'w2:', w2, 'b:', b, 'loss:', loss)

    return w1, w2, b

In [ ]:
mini_model2=ANN()
mini_model2.fit(X_train_scaled,y_train,1000,7)

Epoch: 0 w1: 0.9695545538511102 w2: 0.8606073605256206 b: -0.1593777749912791 loss: 0.8917571931390118
Epoch: 1 w1: 0.9572253187119656 w2: 0.8581982054498064 b: -0.21762949416084534 loss: 0.6136408618470656
Epoch: 2 w1: 0.947026354688556 w2: 0.8269884700378047 b: -0.2895233384333783 loss: 0.6296494752240298
Epoch: 3 w1: 0.9213133700230167 w2: 0.8164458784408682 b: -0.3822083492313848 loss: 0.6607127379725395
Epoch: 4 w1: 0.9351485501967578 w2: 0.8040795847268294 b: -0.4277456183080564 loss: 0.583307824378316
Epoch: 5 w1: 0.9721619024431585 w2: 0.8185821052045184 b: -0.4132430978303675 loss: 0.540101839974822
Epoch: 6 w1: 1.0035629843006184 w2: 0.8073922710385584 b: -0.38568662973444917 loss: 0.6054493713042665
Epoch: 7 w1: 1.051880049259704 w2: 0.8592000112601048 b: -0.2957611725275202 loss: 0.5004682595262427
Epoch: 8 w1: 1.059103961242577 w2: 0.763967593209843 b: -0.3546938008942807 loss: 0.7160979320224791
Epoch: 9 w1: 1.0701511041211875 w2: 0.7760856717006793 b: -0.3845865828780853